version: '3.8'
services:
  discovery:
    image: kyrylobulyk/delivery-discovery:0.0.1
    ports:
      - "8761:8761"
    networks:
      - delivery-network

  users-microservice:
    image: kyrylobulyk/delivery-users-microservice:0.0.1
    depends_on:
      - discovery
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka
    ports:
      - "8080:8080"
    networks:
      - delivery-network

  api-gateway:
    image: kyrylobulyk/delivery-api-gateway:0.0.1
    depends_on:
      - discovery
      - users-microservice
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka
    ports:
      - "8765:8765"
    networks:
      - delivery-network

networks:
  delivery-network:
    driver: bridge
